
name: water_management_app
description: Spink Water Management App (Owner + Driver)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dio: ^5.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^4.0.1
  shared_preferences: ^2.1.1
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/langs/en.json
    - assets/langs/ur.json
    - assets/icon.png
